openapi: 3.0.0
info:
  title: 'Pet Shop API - Swagger Documentation'
  version: 1.0.0
paths:
  /api/v1/admin/create:
    post:
      operationId: adfd219fe5c92529a9cb535d258c2f80
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  /api/v1/admin/login:
    post:
      operationId: 5a40c8e5833e64b90cb28af5048e12c2
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  /api/v1/admin/logout:
    get:
      operationId: e87c8bf7d33c4a933cf7174a5d36a270
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  '/api/v1/admin/user-delete/{uuid}':
    get:
      operationId: f46c06f2db6bd9f22566d7899c39056c
      parameters:
        -
          name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  '/api/v1/admin/user-edit/{uuid}':
    put:
      operationId: d1333ebad88321674c564aa94807ee16
      parameters:
        -
          name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  /api/v1/admin/user-listing:
    put:
      operationId: 24bba07f28468afce53457c8ba2409f6
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  /api/v1/bacs:
    get:
      operationId: bdfd7b90fc16856aad8db2a99ae14e6f
      parameters:
        - name: serial_number
          in: query
          required: true
          schema:
            description: 'Must be a 6 alphanumeric characters.'
            type: string
        - name: sun
          in: query
          required: false
          schema:
            description: "Must be a 6 characters if marker isn't defined."
            type: string
        - name: marker
          in: query
          required: false
          schema:
            description: "Must be hsbc or sage if sun isn't defined."
            type: string
            enum:
              - hsbc
              - sage
        - name: generation_number
          in: query
          required: false
          schema:
            description: 'Must be a number of 4 characters.'
            type: number
        - name: generation_version_number
          in: query
          required: false
          schema:
            description: 'Must be a number of 2 characters.'
            type: number
        - name: fast_payment
          in: query
          required: false
          schema:
            description: 'Indicates if must be fast payment.'
            type: string
        - name: creation_date
          in: query
          required: false
          schema:
            description: "Must be a date in format Y-m-d and explicit defined if fast_payment isn't defined. (ie: 2023-12-03)"
            type: string
        - name: expiration_date
          in: query
          required: false
          schema:
            description: "Must be a date in format Y-m-d and explicit defined if fast_payment isn't defined. (ie: 2023-12-03)"
            type: string
        - name: Accept
          in: header
          required: true
          schema:
            description: 'Must be application/json'
            type: string
            default: application/json
      responses:
        '200':
          description: Success
          content:
            application/json: { }
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        uuid:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        email_verified_at:
          type: string
        avatar:
          type: string
        address:
          type: string
        phone_number:
          type: string
        is_marketing:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string
        last_login_at:
          type: string
      type: object
